export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  MODERATOR = 'MODERATOR',
  SUPPORT_AGENT = 'SUPPORT_AGENT',
  FINANCE_MANAGER = 'FINANCE_MANAGER',
  MARKETING_MANAGER = 'MARKETING_MANAGER',
  EMPLOYER = 'EMPLOYER',
  RECRUITER = 'RECRUITER',
  JOB_SEEKER = 'JOB_SEEKER',
}
